#!/bin/bash

wget --no-check-certificate https://raw.githubusercontent.com/unicode-org/cldr/master/common/supplemental/windowsZones.xml -O windowsZones.xml > /dev/null 2>&1
./zones.pl ~/stuff/wine/dlls/tzres/tzres.rc > zones.c
gcc -Wall -I$(dirname $(which wine64))/../include/wine/windows -o tzinfgen tzinfgen.c
./tzinfgen > tz.inf.in
