1 stub DllCanUnloadNow
2 stub DllGetActivationFactory
3 stub DllGetClassObject
4 stub DllRegisterServer
5 stub DllUnregisterServer
6 stub SpellerCheck
7 stub SpellerCloseLex
8 stub SpellerGetOptions
9 stub SpellerInit
10 stub SpellerOpenLex
11 stub SpellerSetOptions
12 stub SpellerTerminate
